# Generated by Django 2.2.4 on 2019-10-21 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bride', models.CharField(max_length=50)),
                ('groom', models.CharField(max_length=50)),
                ('place_name', models.CharField(max_length=50)),
                ('place_address', models.TextField()),
                ('start_time', models.CharField(max_length=50)),
                ('howtobus', models.TextField()),
                ('howtosubway', models.TextField()),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
