# Generated by Django 2.2.4 on 2019-10-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='template',
            field=models.IntegerField(default=1),
        ),
    ]
